name: Python application

permissions: write-all

on:
  push:
  pull_request:

jobs:
  server:
  
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Run server in the background
      run: |
         sudo python Project/src/main.py &

    - name: Run tests and collect coverage
      run: |
        coverage run -m pytest

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

    - name: Generate report with lizard
      run: lizard > lizard-relat贸rio.txt

    - name: Salvar relat贸rio lizard no reposit贸rio
      uses: test-room-7/action-update-file@v1
      with:
          file-path: lizard-relat贸rio.txt
          commit-msg: Auto generated lizard report
          github-token: ${{ secrets.GITHUB_TOKEN }}    

